name: pomodoro_desktop
description: "Pomodoro Timer avec animations, notifications, et blocage d’apps."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  win32: ^5.0.9
  ffi: ^2.1.4
  win_toast: ^0.1.1
  process_run: ^0.12.3+2
  confetti: ^0.8.0
  audioplayers: ^6.5.0
  supabase_flutter: ^1.10.5
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.66.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/sounds/success.mp3
    - lib/assets/gif/piplup-discord.gif
    - lib/assets/gif/arceus.gif
    - lib/assets/gif/arceus-pokémon.gif
